# Base image
FROM node
# Make folder to put our files in
RUN mkdir -p /usr/src/app
RUN mkdir -p /usr/src/app/Server
# Set working directory so that all subsequent command runs in this folder
WORKDIR /usr/src/app/Server
# Copy package json and install dependencies
COPY package*.json ./
RUN npm install
# Copy our app
COPY . .
# Expose port to access server
EXPOSE 4308
# Command to run our app
CMD [ "npm" , "run" , "start:prod" ]
